prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

grafana:
  dashboards:
    default:
      geth-metrics:
        json: |
          $(cat dashboards/geth-metrics.json)
