apiVersion: v1
kind: ConfigMap
metadata:
  name: geth-health-check
  namespace: {{ .Release.Namespace }}
data:
  check-node-sync.sh: |
    #!/bin/sh
    response=$(curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' http://localhost:8545)
    if echo "$response" | grep -q "false"; then
      # Node is synced
      exit 0
    elif echo "$response" | grep -q "currentBlock"; then
      # Node is syncing
      exit 0
    else
      # Node is not responding correctly
      exit 1
    fi

  check-node-health.sh: |
    #!/bin/sh
    # Check if node is responding to basic requests
    response=$(curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1}' http://localhost:8545)
    if echo "$response" | grep -q "result"; then
      exit 0
    else
      exit 1
    fi