apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: http-rpc
    - name: ws-rpc
      port: {{ .Values.service.wsPort }}
      targetPort: ws-rpc
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    app: {{ .Release.Name }}
