apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - name: http-rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: http-rpc
    - name: ws-rpc
      port: {{ .Values.service.wsPort }}
      targetPort: ws-rpc
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
    - name: p2p-tcp
      port: 30303
      targetPort: p2p-tcp
    - name: p2p-udp
      port: 30303
      targetPort: p2p-udp
      protocol: UDP
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}